# Generated by Django 5.2.8 on 2025-12-08 08:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WheelOfLife",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("health", models.IntegerField(default=5)),
                ("emotions", models.IntegerField(default=5)),
                ("relationships", models.IntegerField(default=5)),
                ("family", models.IntegerField(default=5)),
                ("personal_growth", models.IntegerField(default=5)),
                ("finances", models.IntegerField(default=5)),
                ("career_study", models.IntegerField(default=5)),
                ("rest_hobby", models.IntegerField(default=5)),
                ("environment", models.IntegerField(default=5)),
                ("spirituality", models.IntegerField(default=5)),
                ("creativity", models.IntegerField(default=5)),
                ("contribution", models.IntegerField(default=5)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Колесо баланса жизни",
                "ordering": ["-created_at"],
            },
        ),
    ]
