# Generated by Django 5.2.8 on 2025-12-26 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("growth", "0003_habit"),
    ]

    operations = [
        migrations.RenameField(
            model_name="wheeloflife",
            old_name="career_study",
            new_name="Волонтёрство",
        ),
        migrations.RenameField(
            model_name="wheeloflife",
            old_name="contribution",
            new_name="Друзья",
        ),
        migrations.RenameField(
            model_name="wheeloflife",
            old_name="creativity",
            new_name="Здоровье",
        ),
        migrations.RenameField(
            model_name="wheeloflife",
            old_name="emotions",
            new_name="Личностныйрост",
        ),
        migrations.RenameField(
            model_name="wheeloflife",
            old_name="environment",
            new_name="Отношения",
        ),
        migrations.RenameField(
            model_name="wheeloflife",
            old_name="family",
            new_name="Семья",
        ),
        migrations.RenameField(
            model_name="wheeloflife",
            old_name="finances",
            new_name="Удовлетворенность",
        ),
        migrations.RenameField(
            model_name="wheeloflife",
            old_name="health",
            new_name="Уровень_счатья",
        ),
        migrations.RenameField(
            model_name="wheeloflife",
            old_name="personal_growth",
            new_name="Учеба",
        ),
        migrations.RenameField(
            model_name="wheeloflife",
            old_name="relationships",
            new_name="Финанасы",
        ),
        migrations.RenameField(
            model_name="wheeloflife",
            old_name="rest_hobby",
            new_name="Хобби",
        ),
        migrations.RenameField(
            model_name="wheeloflife",
            old_name="spirituality",
            new_name="Чтение",
        ),
    ]
